Added sample program demonstrating EXI with Exificient
OpenDFDL/examples pull request #28
Opened 2022-11-30 23:10 UTC by jadams-tresys

HelloWorldExificient demonstrates how to use Exificient to:
 - Parse incoming data into an EXI infoset
 - Transform the EXI infoset using an XSLT
 - Unparse the EXI infoset back to original format with changes made by the XSLT

2022-11-30 23:11 UTC, jadams-tresys commented
I intend to bring the AgileDelta example program up to par with this one (using XSLT etc.) once we resolve the license issues.

2022-12-01 17:47 UTC, mbeckerle requested changes
Would like to see documentation/comments in the code improved to explain better what is going on, and some renaming of vars to clarify.

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		exiFactory.getEncodingOptions().setOption(EncodingOptions.INCLUDE_OPTIONS);
I have an EXI question. Only peripherally releated to review of this code. 

Does a schema-aware EXI file contain enough information that one could examine it, and determine say, the namespace of the root element?  Or is that information actually only in the XML Schema itself?

I'd like to be able to carry around schema-ware EXI, and when I need to process such, look up the corresponding XSD in a metadata repository based on using the root element namespace as key. 

Analogous to looking at an XML text document and knowing the namespace URI of the root element. One could use that as a key to find the XSD in a metadata repo, enabling schema-aware processing of the XML text.

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		EXISource exiSource = new EXISource(exiFactory);
Add comments here explaining that we are setting up the XSLT transform to consume SAX events from the EXI data, and to produce SAX events for the transform result, and that those will be directly converted into schema-aware EXI also, so that there is never XML text being created or used here.

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		EXISource unparseExiSource = new EXISource(exiFactory);
Suggest removing the "unparse" prefix from all the exi-related names in this try block. 
Suggest names should be:
```
EXISource exiSource = ...
XMLReader exiReader = ...
```

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		unparseXMLReader.parse(unparseInputSource);
Add comment to this line. // 'parse' the EXI data to SAX events which drive the unparsing. "

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/src/test/java/TestHelloWorldExificient.java
> +      Assert.fail("Should not have thrown any exception");
Suggest just leaving off this try-catch. If a throw occurs the test fails, and that way you get a back-trace, and can see what exception it was.

2022-12-01 17:47 UTC, mbeckerle commented on helloWorldExificient/README.txt
> +This is a Daffodil/DFDL hello-world program using the Exificient library to support EXI infosets.
Add to this Readme.txt explaination that motivates this example:

1) avoids any use of XML text - i.e., illustrates how to DFDL parse, XSLT transform, and DFDL unparse data without ever creating any large/expensive XML text. 

2) shows use of EXI and SAX APIs to do XSLT transformation of the EXI data

2022-12-01 19:33 UTC, stevedlawrence reviewed
Agreed with Mike. Lot's more comments would be helpful.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/README.txt
> +This is a Daffodil/DFDL hello-world program using the Exificient library to support EXI infosets.
Also I'd suggest making this a .md file so it's a bit prettier when viewed in GitHub.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/.project
> +</projectDescription>
In Daffodil and other DFDL projects we haven't included IDE specific files. Should we remove this?

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/README.txt
> +The jar files are cached in the lib_managed/ directory (which is removed by 'sbt clean')
Alot of this is standard build tool stuff that I wouldn't think most people would need to know, or would already know (like needing an internet connection to download dependencies. I think `sbt run` (and the stuff mike mentioned) is really all users need to know.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +	InputStream originalData = dataFileURL.openStream();
Indentation is inconsistent in this file.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		parseExiResult.setOutputStream(parseOs);
Does it make sense to do these two lines outside of this try block, just to make it more clear that the other lines here are just about schema aware exi and this two are required regardless. Even if it needs a separate try block, I think it makes it easier to follow as an example.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +	ParseResult res = (ParseResult) reader.getProperty("urn:ogf:dfdl:2013:imp:daffodil.apache.org:2018:sax:ParseResult");
We can use `DaffodilParseXMLReader.DAFFODIL_SAX_URN_PARSERESULT` instead of copy/pasting the string.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +	byte[] parsedBytes = parseOs.toByteArray();
Thoughts on naming this exiBytes or something? I initially read this as the bytes that are going to be parsed and was confused.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		EXISource exiSource = new EXISource(exiFactory);
Agreed, I think each hunk of data could use comments, even if they are pretty obvious. This is a hello world example that people will use to understand the flow and logic, so lots of comments will make things much easier.

It might even mean breaking up code into multiple sections just to make it more clear exactly what does what.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
So this transforms one EXI file to another EXI file? I guess in theory we could link a bunch of transforms or something so we go straight from EXI file to XSLT to Daffodil Unparse without any serialization inbetween? I don't suggest we do that here, but would be needed for a solution that streams end-to-end.

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		System.exit(1);
Sugges just catching generic Exception? This is a hello world so keeping things clear and concise might be more important than catching specific exceptions?

2022-12-01 19:33 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +        // schema if you only intend to do parsing.
This feels like extraneous information and might just get in the way of people trying to focus on how to do EXI with Daffodil. We know this schema can unparse, and it's pretty rare for schemas to not be able to unparse.

2022-12-01 20:01 UTC, tuxji requested changes
Would like some changes.

2022-12-01 20:37 UTC, tuxji commented on helloWorldExificient/src/test/java/TestHelloWorldExificient.java
> +       HelloWorldExificient.main(new String[0]);
Er, actually you need `String[] args = { "no args" };` and then pass `args` (not sure you can inline a `{ }` expression into the main() call).

2022-12-01 21:31 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
I think that "all hooked together" so that we don't even create EXI is another different example we should create. 

But it's not this one. This one is about showing you can use XML via EXI, schema-aware, and not have to ever create XML text.

2022-12-01 21:34 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		System.exit(1);
I actually like showing the different kinds of exceptions that can be thrown. It's more clutter, but makes the point that things can go wrong with the EXI (e.g., the EXI input was somehow clobbered/broken) vs. something going wrong in the XSLT transformation itself.

2022-12-02 00:48 UTC, jadams-tresys commented on helloWorldExificient/.project
> +</projectDescription>
This was simply there from the original helloWorld project that I copied the initial project structure from.

2022-12-02 00:53 UTC, jadams-tresys commented on helloWorldExificient/project/build.properties
> +sbt.version=1.6.1
Will do

2022-12-02 00:59 UTC, jadams-tresys commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +	InputStream originalData = dataFileURL.openStream();
Didn't realize that my editor was using tabs instead of 8 spaces.  Will do a file wide switch to everything being 4 spaces in a separate commit so that it's easy to see what changed when.

2022-12-02 01:02 UTC, jadams-tresys commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		parseExiResult.setOutputStream(parseOs);
I originally did, but the constructor of the EXIResult can throw EXIException.

2022-12-02 01:11 UTC, jadams-tresys commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
Yes, it should be possible to avoid creating a second EXI file just for the transform.  Figured being explicit was good for an introductory example.  As for the end-to-end streaming, if it's truly end-to-end would you even want to use EXI instead of just routing SAX events from parse->transform->unparse?   Then we would never have a fully fleshed out infoset being created.

2022-12-02 12:20 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
Agreed we definitely want a second EXI in his example. Yeah, for a end-to-end streaming example EXI probably wouldn't be necessary.

I wasn't clear, but I was originally asking if transforms are the way to chain together sax events, seems like that's he case.

2022-12-02 14:31 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +	InputStream originalData = dataFileURL.openStream();
Actually, our standard is indent 2 spaces, not 4.

2022-12-02 14:50 UTC, mbeckerle commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
I guess the requirements (that I had in mind) for this example were never articulated.

Many people who use Daffodil in Cyberia are currently carrying XML text via staging data to files or via some sort of IPC between isolated processes, and they incur the overhead of reparsing that XML text in every process to access the data, and then reserializing back to XML text on the way out. 

Without creating such a process and files/IPC framework (which is too complex) a goal of this example is to show:

(a) how to replace XML Text with EXI bytes

(b) how to use SAX with Daffodil and with XSLT both on the input and output side. 

I.e., the lowest-overhead way to process DFDL-described data that is still consistent with eventually using IPC between processes of "the XML" (formerly as XML text, now as EXI). 

An example that hooks everything together via SAX API calls would be cool to have (and measure), but that's not consistent with the isolated processes of many Daffodil applications in the cyberian space. 

 A really important part of this example is showing that in order to use EXI (schema aware), every processing stage needs the XSD schema, because the EXI (schema-aware) data cannot be reconstituted into SAX events without it.

2022-12-02 15:10 UTC, stevedlawrence commented on helloWorldExificient/src/main/java/HelloWorldExificient.java
> +		tr.transform(exiSource, transformExiResult);
Agreed. Sorry for making things confusing.

2022-12-05 15:09 UTC, mbeckerle approved these changes
+1

2022-12-15 19:43 UTC, mbeckerle commented
@jadams-tresys when do you think this can be finished up? This example is quite important for Daffodil 3.4.0 users.

2022-12-15 19:56 UTC, jadams-tresys commented
I should have this finished by tomorrow morning most likely.  Just wrapping up some of the cleanup that @uxji mentioned (moving things out to separate functions, etc.)

2022-12-16 15:03 UTC, jadams-tresys commented
Should hopefully have addressed all comments from review now.  Reorganized things to hopefully be a little more clear as to what is going on.

2022-12-19 15:38 UTC, tuxji approved these changes
+1

I want to leave everyone with this thought for future PRs.  A good example is an example of many things including good indentation/code style, good error/defensive programming practices, and more.  You want to show all of these as well as the function the example performs.

2022-12-19 17:09 UTC, mbeckerle approved these changes
+1 

When I read java code I'm always very glad I mostly use Scala. 350+ LoC for parse/xform/unparse is a lot of clutter.

2022-12-19 18:44 UTC, merged